# Project Specific
version=1.21.1-v13
group=com.yyon
mod_name=Grappling Hook Mod
mod_author=Yyon, Nyfaria, and Mayesnake
mod_id=grapplemod
description=A mod which adds grappling hooks. The aim of this mod is to provide a fun way to get around large builds like cities.
credits=Textures by Mayesnake
curseforge_publishing_enabled=true
curseforge_project_id=238911
modrinth_publishing_enabled=true
modrinth_project_id=hGWjTxOA
dry_run=false

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Common
minecraft_version=1.21.1
java_version=21
license=GPL-3.0
