plugins {
    id 'multiloader-common'
    alias(nyfs.plugins.mdg.loader)
    alias(nyfs.plugins.regutils.loader)
    id 'multiloader-vanilla'
}

dependencies {
    compileOnly(nyfs.bundles.mixin.common.get())
    annotationProcessor nyfs.mixin.extras.common.get()
    compileOnly nyfs.config.api.common.get()
}
